# Generated by Django 6.0 on 2026-01-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bio',
            old_name='career_goal',
            new_name='my_goals',
        ),
        migrations.AddField(
            model_name='bio',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='how_i_learn',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bio',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='what_i_know',
            field=models.TextField(default='', help_text='Separate items with new lines'),
            preserve_default=False,
        ),
    ]
